import MODULES from "./modules.js";
import PERMISSIONS from "./permissions.js";

const ROLE_PERMISSIONS = {
  1: { // Hon. Collector
    [MODULES.DASHBOARD]: [PERMISSIONS.VIEW],
    [MODULES.USERS]: [PERMISSIONS.VIEW, PERMISSIONS.READ],
    [MODULES.REPORTS]: [PERMISSIONS.VIEW, PERMISSIONS.READ],
  },

  2: { // Organiser (Admin)
    [MODULES.DASHBOARD]: [PERMISSIONS.VIEW],
    [MODULES.USERS]: [
      PERMISSIONS.VIEW,
      PERMISSIONS.READ,
      PERMISSIONS.CREATE,
      PERMISSIONS.UPDATE,
      PERMISSIONS.DELETE,
    ],
    [MODULES.MEETINGS]: [
      PERMISSIONS.VIEW,
      PERMISSIONS.READ,
      PERMISSIONS.CREATE,
      PERMISSIONS.UPDATE,
    ],
    [MODULES.REPORTS]: [
      PERMISSIONS.VIEW,
      PERMISSIONS.READ,
      PERMISSIONS.CREATE,
    ],
  },

  3: { // HOD
    [MODULES.DASHBOARD]: [PERMISSIONS.VIEW],
    [MODULES.MEETINGS]: [
      PERMISSIONS.VIEW,
      PERMISSIONS.READ,
      PERMISSIONS.UPDATE,
    ],
  },
};

export default ROLE_PERMISSIONS;